version: '3'
services:  
    receipt:
        build: ./receiptGenerator
        volumes:
            - ./receiptGenerator:/app
        ports:
            - "8000:80"
        command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:80"
        restart: always