version: '3'

services:
  cassandra0:
    image: bitnami/cassandra:latest
    ports:
      - '7000:7000'
      - '9042:9042'
      - '7199:7199'
    volumes:
      - 'cassandra0_data:/bitnami'
      - 'init-scripts:/docker-entrypoint-initdb.d'
    environment:
      - CASSANDRA_SEEDS=cassandra0
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_CLUSTER_NAME=dht
  cassandra1:
    image: bitnami/cassandra:latest
    volumes:
      - 'cassandra1_data:/bitnami'
    environment:
      - CASSANDRA_SEEDS=cassandra0
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_CLUSTER_NAME=dht

volumes:
  init-scripts:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./init-scripts
  cassandra0_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./dht0
  cassandra1_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./dht1
