version: '3'
services:
    postgres:
        restart: always
        image: postgres:latest
        volumes:
            - postgres-storage:/var/lib/postgres
        environment:
            - POSTGRES_ROOT_PASSWORD= ${POSTGRES_ROOT_PASSWORD}
            - POSTGRES_DATABASE= postgresdb
            - POSTGRES_USER= ${POSTGRES_USER}
            - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}
        restart: always

    receiptgenerator:
        build: ./receiptGenerator
        volumes:
            - ./receiptGenerator:/app
        ports:
            - "8000:80"
        command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:80"
        restart: always

volumes:
    postgres-storage:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: ./postgres
        